name: Scrape Couple

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 12 */2 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "npm"
      - name: Install dependencies
        run: npm i -g yarn && yarn install
      - name: Start scrape data of couple
        run: yarn scrape:couple
      - name: Commit and push if it changed
        run: |-
          git config user.name "satyawikananda"
          git config user.email "${{ secrets.EMAIL }}"
          git add -A
          timestamp=$(date -u)
          git commit -m "chore(data): Update scrape data of couple" || exit 0
          git push